# -*- mode: ruby -*-
# vi: set ft=ruby :

nodes = [
  { :hostname => 'testserver', :ip => '10.1.6.211' }
]

Vagrant.configure(2) do |config|

  nodes.each do |node|
    config.vm.define node[:hostname] do |nodeconfig|

       nodeconfig.vm.box = "bento/centos-7.3"
       nodeconfig.vm.box_version = "2.3.5"
        #nodeconfig.vm.box = "centos/7"
        #nodeconfig.vm.box_version = "1704.01"
        nodeconfig.vm.network "public_network", ip:node[:ip], netmask: "255.0.0.0", bridge:"enp8s0"
        nodeconfig.vm.hostname = node[:hostname]
        nodeconfig.vm.provider "virtualbox" do |vb|
          vb.memory = "4096"
          vb.cpus = "2"
        end
        nodeconfig.vm.provision "shell", path: "../script/common.sh"
        nodeconfig.vm.synced_folder "../initstorage/", "/vagrant", create: true
       #nodeconfig.vm.synced_folder "../initstorage/", "/vagrant", id: "core", create: true, owner: "root", group: "root"
       
      
      # 增加 second 硬碟
      #file_to_disk = 'D:/UniServerZ/www/VM/tealit.com/large_disk.vdi'
      #unless File.exist?(file_to_disk)
      #  vb.customize ['createhd', '--filename', file_to_disk, '--size', 500 * 1024]
      #end
      #vb.customize ['storageattach', :id, '--storagectl', 'SATA Controller', '--port', 1, '--device', 0, '--type', 'hdd', '--medium', file_to_disk]

    end
  end
end
