#!/bin/bash


filename1="./vmList.txt"
filename2="./vmSnapshot_temp.txt"
echo $filename1

#檢查檔案是否存在
#if [ -d "/path/to/dir" ]; then
    # 目錄 /path/to/dir 存在
    # echo "Directory /path/to/dir exists."
#else
    # 目錄 /path/to/dir 不存在
    # echo "Directory /path/to/dir does not exists."
#fi

if [ -f $filename ]; then
    # 檔案 /path/to/dir/filename 存在
    echo "Update " $filename1 
    rm -rf $filename
else
    # 檔案 /path/to/dir/filename 不存在
    echo "File " $filename1 " does not exists."
fi

echo "**** Get all vms to file ****"

VBoxManage list vms > $filename1

echo "**** Get vm and snapshot ****"

exec < $filename1
while read line
do
  echo $line
  nnn=( $line )
  #echo "s1 : '${nnn[0]}'"
  #echo "s2 : '${nnn[1]}'"
  #echo "sn : '${#nnn[@]}'"

  VBoxManage snapshot ${nnn[1]} list > $filename2

  while read line2
  do
    IFS=$' ' DIRS=(${line2})
    for (( i=0 ; i<${#DIRS[@]} ; i++ ));
    do
        echo "$i: [${DIRS[i]}]"
    done
  done < $filename2


done
